# prometheus.yml

global:
  scrape_interval: 15s  # How often Prometheus scrapes targets.
  evaluation_interval: 15s  # How often to evaluate rules.

scrape_configs:
  - job_name: "app_metrics"
    static_configs:
      - targets: ["localhost:8001"]  # Metrics server started by your app
          
  - job_name: "system_metrics"
    static_configs:
      - targets: ["localhost:9100"]  # Node exporter for system-level metrics.
  
  - job_name: "database_metrics"
    static_configs:
      - targets: ["localhost:9187"]  # PostgreSQL exporter.
